version: "3.9"  # optional since v1.27.0
services:
    api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8080:80"
        depends_on:
          - db
    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports: # not actually needed, because the two services are on the same network
          - "1433:1433" 
        environment:
            SA_PASSWORD: "yourStrongPassword123"
            ACCEPT_EULA: "Y"